# -*- coding: utf-8 -*-
"""EE604A_HA1_Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IVXMC18vu-YjOQuEFNbk8qNplkfkpcLr
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
# import matplotlib.image as mpimg
import sys
from PIL import Image
# from google.colab.patches import cv2_imshow
# from google.colab import files

# uploaded = files.upload()

input_img= sys.argv[1]
imag = Image.open(input_img)
img = np.array(imag)
#img=arr[:,:,[2,1,0]]#bgr

# dim=img.shape;
# print(dim[0],dim[1])
# plt.imshow(img)

part1=img[0:200,0:190]
part1=part1[:,:,[0,2,1]]#rbg
# plt.imshow(part1)

part2=img[200:410,0:190]
part2=cv2.flip(part2,0)
# plt.imshow(part2)


img[0:210,0:190]=part2
img[200:400,0:190]=part1

part3=img[150:330,515:700]
part3=cv2.flip(part3,1)
img[150:330,515:700]=part3

part4=img[370:421,370:797]
part4=cv2.flip(part4,0)
img[370:421,370:797]=part4
# plt.imshow(part4)

pad1=img[395:400,0:190]
pad2=img[410:415,0:190]
img[400:405,0:190]=pad1
img[405:410,0:190]=pad2

# padnew=img[395:415,0:190]
img = Image.fromarray(img)
plt.imshow(img)
img.show()